var searchData=
[
  ['segmentedvector_0',['SegmentedVector',['../classNeoN_1_1SegmentedVector.html',1,'NeoN']]],
  ['segmentedvector_3c_20localidx_2c_20localidx_20_3e_1',['SegmentedVector&lt; localIdx, localIdx &gt;',['../classNeoN_1_1SegmentedVector.html',1,'NeoN']]],
  ['segmentedvectorview_2',['SegmentedVectorView',['../classNeoN_1_1SegmentedVectorView.html',1,'NeoN']]],
  ['serialexecutor_3',['SerialExecutor',['../classNeoN_1_1SerialExecutor.html',1,'NeoN']]],
  ['solver_4',['Solver',['../classNeoN_1_1la_1_1Solver.html',1,'NeoN::la']]],
  ['solverfactory_5',['SolverFactory',['../classNeoN_1_1la_1_1SolverFactory.html',1,'NeoN::la']]],
  ['solverstats_6',['SolverStats',['../structNeoN_1_1la_1_1SolverStats.html',1,'NeoN::la']]],
  ['solverstatsentry_7',['SolverStatsEntry',['../structNeoN_1_1la_1_1SolverStatsEntry.html',1,'NeoN::la']]],
  ['sourceterm_8',['SourceTerm',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SourceTerm.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['sparsityview_9',['SparsityView',['../structNeoN_1_1la_1_1SparsityView.html',1,'NeoN::la']]],
  ['spatialoperator_10',['SpatialOperator',['../classNeoN_1_1dsl_1_1SpatialOperator.html',1,'NeoN::dsl']]],
  ['supportscopyto_11',['SupportsCopyTo',['../classNeoN_1_1SupportsCopyTo.html',1,'NeoN']]],
  ['supportscopyto_3c_20coosparsitypattern_3c_20indextype_20_3e_20_3e_12',['SupportsCopyTo&lt; CooSparsityPattern&lt; IndexType &gt; &gt;',['../classNeoN_1_1SupportsCopyTo.html',1,'NeoN']]],
  ['supportscopyto_3c_20csrsparsitypattern_3c_20indextype_20_3e_20_3e_13',['SupportsCopyTo&lt; CsrSparsityPattern&lt; IndexType &gt; &gt;',['../classNeoN_1_1SupportsCopyTo.html',1,'NeoN']]],
  ['supportscopyto_3c_20facetomatrixaddress_20_3e_14',['SupportsCopyTo&lt; FaceToMatrixAddress &gt;',['../classNeoN_1_1SupportsCopyTo.html',1,'NeoN']]],
  ['supportscopyto_3c_20matrix_3c_20valuetype_2c_20localidx_20_3e_20_3e_15',['SupportsCopyTo&lt; Matrix&lt; ValueType, localIdx &gt; &gt;',['../classNeoN_1_1SupportsCopyTo.html',1,'NeoN']]],
  ['supportscopyto_3c_20matrix_3c_20valuetype_2c_20sparsitytype_20_3e_20_3e_16',['SupportsCopyTo&lt; Matrix&lt; ValueType, SparsityType &gt; &gt;',['../classNeoN_1_1SupportsCopyTo.html',1,'NeoN']]],
  ['supportscopyto_3c_20segmentedvector_3c_20localidx_2c_20localidx_20_3e_20_3e_17',['SupportsCopyTo&lt; SegmentedVector&lt; localIdx, localIdx &gt; &gt;',['../classNeoN_1_1SupportsCopyTo.html',1,'NeoN']]],
  ['supportscopyto_3c_20segmentedvector_3c_20valuetype_2c_20indextype_20_3e_20_3e_18',['SupportsCopyTo&lt; SegmentedVector&lt; ValueType, IndexType &gt; &gt;',['../classNeoN_1_1SupportsCopyTo.html',1,'NeoN']]],
  ['supportsloggingmixin_19',['SupportsLoggingMixin',['../classNeoN_1_1Logging_1_1SupportsLoggingMixin.html',1,'NeoN::Logging']]],
  ['surfaceboundary_20',['SurfaceBoundary',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceBoundary.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceboundaryfactory_21',['SurfaceBoundaryFactory',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceBoundaryFactory.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfacefield_22',['SurfaceField',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceField.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfacefield_3c_20neon_3a_3ascalar_20_3e_23',['SurfaceField&lt; NeoN::scalar &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceField.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfacefield_3c_20neon_3a_3avec3_20_3e_24',['SurfaceField&lt; NeoN::Vec3 &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceField.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfacefield_3c_20scalar_20_3e_25',['SurfaceField&lt; scalar &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceField.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceintegrate_26',['SurfaceIntegrate',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceIntegrate.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceinterpolation_27',['SurfaceInterpolation',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceInterpolation.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceinterpolation_3c_20neon_3a_3avec3_20_3e_28',['SurfaceInterpolation&lt; NeoN::Vec3 &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceInterpolation.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceinterpolation_3c_20scalar_20_3e_29',['SurfaceInterpolation&lt; scalar &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceInterpolation.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceinterpolationfactory_30',['SurfaceInterpolationFactory',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceInterpolationFactory.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['symmetry_31',['symmetry',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1surfaceBoundary_1_1Symmetry.html',1,'NeoN::finiteVolume::cellCentred::surfaceBoundary::Symmetry&lt; ValueType &gt;'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1volumeBoundary_1_1Symmetry.html',1,'NeoN::finiteVolume::cellCentred::volumeBoundary::Symmetry&lt; ValueType &gt;']]],
  ['symmtensor_32',['SymmTensor',['../classNeoN_1_1SymmTensor.html',1,'NeoN']]]
];
