var searchData=
[
  ['segmentedvector_0',['SegmentedVector',['../classNeoN_1_1SegmentedVector.html',1,'NeoN']]],
  ['segmentedvector_3c_20localidx_2c_20localidx_20_3e_1',['SegmentedVector&lt; localIdx, localIdx &gt;',['../classNeoN_1_1SegmentedVector.html',1,'NeoN']]],
  ['segmentedvectorview_2',['SegmentedVectorView',['../classNeoN_1_1SegmentedVectorView.html',1,'NeoN']]],
  ['serialexecutor_3',['SerialExecutor',['../classNeoN_1_1SerialExecutor.html',1,'NeoN']]],
  ['solver_4',['Solver',['../classNeoN_1_1la_1_1Solver.html',1,'NeoN::la']]],
  ['solverfactory_5',['SolverFactory',['../classNeoN_1_1la_1_1SolverFactory.html',1,'NeoN::la']]],
  ['solverstats_6',['SolverStats',['../structNeoN_1_1la_1_1SolverStats.html',1,'NeoN::la']]],
  ['solverstatsentry_7',['SolverStatsEntry',['../structNeoN_1_1la_1_1SolverStatsEntry.html',1,'NeoN::la']]],
  ['sourceterm_8',['SourceTerm',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SourceTerm.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['sparsitypattern_9',['SparsityPattern',['../classNeoN_1_1la_1_1SparsityPattern.html',1,'NeoN::la']]],
  ['sparsityview_10',['SparsityView',['../structNeoN_1_1la_1_1SparsityView.html',1,'NeoN::la']]],
  ['spatialoperator_11',['SpatialOperator',['../classNeoN_1_1dsl_1_1SpatialOperator.html',1,'NeoN::dsl']]],
  ['supportsloggingmixin_12',['SupportsLoggingMixin',['../classNeoN_1_1Logging_1_1SupportsLoggingMixin.html',1,'NeoN::Logging']]],
  ['surfaceboundary_13',['SurfaceBoundary',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceBoundary.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceboundaryfactory_14',['SurfaceBoundaryFactory',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceBoundaryFactory.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfacefield_15',['SurfaceField',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceField.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfacefield_3c_20neon_3a_3ascalar_20_3e_16',['SurfaceField&lt; NeoN::scalar &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceField.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfacefield_3c_20neon_3a_3avec3_20_3e_17',['SurfaceField&lt; NeoN::Vec3 &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceField.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfacefield_3c_20scalar_20_3e_18',['SurfaceField&lt; scalar &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceField.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceintegrate_19',['SurfaceIntegrate',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceIntegrate.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceinterpolation_20',['SurfaceInterpolation',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceInterpolation.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceinterpolation_3c_20neon_3a_3avec3_20_3e_21',['SurfaceInterpolation&lt; NeoN::Vec3 &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceInterpolation.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceinterpolation_3c_20scalar_20_3e_22',['SurfaceInterpolation&lt; scalar &gt;',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceInterpolation.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['surfaceinterpolationfactory_23',['SurfaceInterpolationFactory',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1SurfaceInterpolationFactory.html',1,'NeoN::finiteVolume::cellCentred']]],
  ['symmetry_24',['symmetry',['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1surfaceBoundary_1_1Symmetry.html',1,'NeoN::finiteVolume::cellCentred::surfaceBoundary::Symmetry&lt; ValueType &gt;'],['../classNeoN_1_1finiteVolume_1_1cellCentred_1_1volumeBoundary_1_1Symmetry.html',1,'NeoN::finiteVolume::cellCentred::volumeBoundary::Symmetry&lt; ValueType &gt;']]],
  ['symmtensor_25',['SymmTensor',['../classNeoN_1_1SymmTensor.html',1,'NeoN']]]
];
