name: Build NeoN with sanitizer
run-name: 'Build workflow'

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  schedule:
    - cron: "0 9 * * *"

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1
  LSAN_OPTIONS: suppressions=/home/runner/work/NeoN/NeoN/scripts/san_ignores.txt


concurrency:
  group: >
    ${{ github.workflow }}-
    ${{ github.event_name }}-
    ${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    if: >
      github.repository == 'exasim-project/NeoN' &&
      (github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'full-ci'))
    name: Build NeoN with sanitizer
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - CC: gcc
            CXX: g++
        preset: ["NeoN_ENABLE_SANITIZE_ADDRESS=ON",
          "NeoN_ENABLE_SANITIZE_UB=ON"
        ]
    runs-on: ubuntu-latest
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v4

     - name: Set up cache
       uses: actions/cache@v4
       if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip-cache')}}
       with:
         path: build
         key: san_build_${{ github.event.pull_request.number || github.ref_name }}_${{matrix.preset}}_${{ github.sha }}
         restore-keys: san_build_${{ github.event.pull_request.number || github.ref_name }}_${{matrix.preset}}_

     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y \
           ninja-build \
           python3 \
           python3-dev \
           build-essential \
           libopenmpi-dev \
           openmpi-bin

     - name: Get versions
       run: |
         g++ --version
         ninja --version
         cmake --version

     - name: Build NeoN
       run: |
         CC=${{matrix.compiler.CC}} \
         CXX=${{matrix.compiler.CXX}} \
         cmake --preset develop -D${{matrix.preset}} \
           -DNeoN_BUILD_TESTS=ON \
           -DNeoN_DEVEL_TOOLS=OFF \
           -DNeoN_ENABLE_MPI_WITH_THREAD_SUPPORT=OFF
         cmake --build  --preset develop

     - name: Execute unit tests NeoN
       run: |
         if [[ "${{matrix.preset}}" == *ADDRESS* ]]; then
           export LD_PRELOAD="$(${{matrix.compiler.CC}} -print-file-name=libasan.so)"
         fi
         ctest --preset develop
