name: Adapter Integration Test
run-name: 'Adapter Integration Test'

on:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  schedule:
    - cron: '00 8 * * 0'
  workflow_dispatch:

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"
    name: Build FoamAdapter
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - CC: clang
            CXX: clang++
          - CC: gcc
            CXX: g++
    runs-on: ubuntu-24.04
    steps:
     - name: Determine branch to checkout
       run: |
         # Use PR head branch if available, otherwise the branch of the push
         BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
         echo "checkout=$BRANCH" >> $GITHUB_ENV

     - name: Checkout FoamAdapter
       uses: actions/checkout@v4
       with:
        repository: exasim-project/FoamAdapter
        ref: '${{ env.checkout }}'

     # Optional NeoN checkout if needed
     # - name: Checkout NeoN submodule
     #   uses: actions/checkout@v4
     #   with:
     #    repository: exasim-project/NeoN
     #    path: NeoN
     #    ref: '${{ env.checkout }}'

     - name: Set up OpenFOAM
       uses: gerlero/setup-openfoam@v1
       with:
         openfoam-version: 2406

     - name: Install dependencies
       uses: gerlero/apt-install@v1
       with:
         packages: >-
           ninja-build
           clang-16
           gcc-10
           libomp-16-dev
           python3
           python3-dev
           build-essential
           libopenmpi-dev
           openmpi-bin

     - name: Get versions
       run: |
         clang --version
         ninja --version
         cmake --version

     - name: Build FoamAdapter
       run: |
         source /usr/lib/openfoam/openfoam2406/etc/bashrc || true
         CC=${{matrix.compiler.CC}} \
         CXX=${{matrix.compiler.CXX}} \
         cmake --preset develop \
           -DNeoN_DEVEL_TOOLS=OFF \
           -DNeoN_BUILD_TESTS=OFF \
           -DFOAMADAPTER_BUILD_BENCHMARKS=OFF \
           -DNeoN_ENABLE_MPI_WITH_THREAD_SUPPORT=OFF \
           -DFOAMADAPTER_NEON_VERSION=${{env.checkout}}
         cmake --build  --preset develop

     - name: Execute unit tests NeoN
       run: |
         source /usr/lib/openfoam/openfoam2406/etc/bashrc || true
         ctest --preset develop
